### ISSUE TITLE
Guidance on API permissions

### ISSUE THREAD

**Issue by Steve-A-Orr** [FullertonLibCode/STIM2022apiTickets#1]
You have a step to "acquire API credentials" but no instructions on accomplishing it. I assumed that you meant for us to log into LibAnswers and use the use the "Add New Application" feature; but I also had to guess at what permissions I was to give it. I went with all (View, Create, Update) scopes.

Is this what you envisioned to be accomplished on this step?

**Comment by quist00** [comment]
Hi, Steve  

Thanks for surfacing that lack of detail.  Yes, users will need to add a new application. The name and description are at their discretion.  Having all the scopes will certainly work, but only create is required for the activities we will be covering. I will update the read me to be more clear.
